//! RPC operation definitions and routing macros.

/// All RPC operations supported by the MISAKA RPC server.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RpcOp {
    Ping,
    GetSystemInfo,
    GetConnections,
    GetMetrics,
    GetBlock,
    GetBlocks,
    GetBlockCount,
    GetBlockDagInfo,
    GetHeaders,
    GetMempoolEntries,
    GetMempoolEntry,
    SubmitTransaction,
    GetUtxosByAddresses,
    GetBalanceByAddress,
    GetBalancesByAddresses,
    GetVirtualChainFromBlock,
    GetSinkBlueScore,
    GetVirtualDaaScore,
    GetBlockTemplate,
    SubmitBlock,
    GetCoinbaseAddress,
    EstimateFeeRate,
    GetPruningPoint,
    ResolveFinalityConflict,
    Subscribe,
    Unsubscribe,
    GetPeerAddresses,
    AddPeer,
    BanPeer,
    UnbanPeer,
    Shutdown,
}

impl RpcOp {
    pub fn from_method(method: &str) -> Option<Self> {
        match method {
            "ping" => Some(Self::Ping),
            "getSystemInfo" => Some(Self::GetSystemInfo),
            "getConnections" => Some(Self::GetConnections),
            "getMetrics" => Some(Self::GetMetrics),
            "getBlock" => Some(Self::GetBlock),
            "getBlocks" => Some(Self::GetBlocks),
            "getBlockCount" => Some(Self::GetBlockCount),
            "getBlockDagInfo" => Some(Self::GetBlockDagInfo),
            "getHeaders" => Some(Self::GetHeaders),
            "getMempoolEntries" => Some(Self::GetMempoolEntries),
            "getMempoolEntry" => Some(Self::GetMempoolEntry),
            "submitTransaction" => Some(Self::SubmitTransaction),
            "getUtxosByAddresses" => Some(Self::GetUtxosByAddresses),
            "getBalanceByAddress" => Some(Self::GetBalanceByAddress),
            "getBalancesByAddresses" => Some(Self::GetBalancesByAddresses),
            "getVirtualChainFromBlock" => Some(Self::GetVirtualChainFromBlock),
            "getSinkBlueScore" => Some(Self::GetSinkBlueScore),
            "getVirtualDaaScore" => Some(Self::GetVirtualDaaScore),
            "getBlockTemplate" => Some(Self::GetBlockTemplate),
            "submitBlock" => Some(Self::SubmitBlock),
            "getCoinbaseAddress" => Some(Self::GetCoinbaseAddress),
            "estimateFeeRate" => Some(Self::EstimateFeeRate),
            "getPruningPoint" => Some(Self::GetPruningPoint),
            "resolveFinalityConflict" => Some(Self::ResolveFinalityConflict),
            "subscribe" => Some(Self::Subscribe),
            "unsubscribe" => Some(Self::Unsubscribe),
            "getPeerAddresses" => Some(Self::GetPeerAddresses),
            "addPeer" => Some(Self::AddPeer),
            "banPeer" => Some(Self::BanPeer),
            "unbanPeer" => Some(Self::UnbanPeer),
            "shutdown" => Some(Self::Shutdown),
            _ => None,
        }
    }

    pub fn method_name(&self) -> &'static str {
        match self {
            Self::Ping => "ping",
            Self::GetSystemInfo => "getSystemInfo",
            Self::GetConnections => "getConnections",
            Self::GetMetrics => "getMetrics",
            Self::GetBlock => "getBlock",
            Self::GetBlocks => "getBlocks",
            Self::GetBlockCount => "getBlockCount",
            Self::GetBlockDagInfo => "getBlockDagInfo",
            Self::GetHeaders => "getHeaders",
            Self::GetMempoolEntries => "getMempoolEntries",
            Self::GetMempoolEntry => "getMempoolEntry",
            Self::SubmitTransaction => "submitTransaction",
            Self::GetUtxosByAddresses => "getUtxosByAddresses",
            Self::GetBalanceByAddress => "getBalanceByAddress",
            Self::GetBalancesByAddresses => "getBalancesByAddresses",
            Self::GetVirtualChainFromBlock => "getVirtualChainFromBlock",
            Self::GetSinkBlueScore => "getSinkBlueScore",
            Self::GetVirtualDaaScore => "getVirtualDaaScore",
            Self::GetBlockTemplate => "getBlockTemplate",
            Self::SubmitBlock => "submitBlock",
            Self::GetCoinbaseAddress => "getCoinbaseAddress",
            Self::EstimateFeeRate => "estimateFeeRate",
            Self::GetPruningPoint => "getPruningPoint",
            Self::ResolveFinalityConflict => "resolveFinalityConflict",
            Self::Subscribe => "subscribe",
            Self::Unsubscribe => "unsubscribe",
            Self::GetPeerAddresses => "getPeerAddresses",
            Self::AddPeer => "addPeer",
            Self::BanPeer => "banPeer",
            Self::UnbanPeer => "unbanPeer",
            Self::Shutdown => "shutdown",
        }
    }

    pub fn all() -> &'static [RpcOp] {
        &[
            Self::Ping,
            Self::GetSystemInfo,
            Self::GetConnections,
            Self::GetMetrics,
            Self::GetBlock,
            Self::GetBlocks,
            Self::GetBlockCount,
            Self::GetBlockDagInfo,
            Self::GetHeaders,
            Self::GetMempoolEntries,
            Self::GetMempoolEntry,
            Self::SubmitTransaction,
            Self::GetUtxosByAddresses,
            Self::GetBalanceByAddress,
            Self::GetBalancesByAddresses,
            Self::GetVirtualChainFromBlock,
            Self::GetSinkBlueScore,
            Self::GetVirtualDaaScore,
            Self::GetBlockTemplate,
            Self::SubmitBlock,
            Self::GetCoinbaseAddress,
            Self::EstimateFeeRate,
            Self::GetPruningPoint,
            Self::ResolveFinalityConflict,
            Self::Subscribe,
            Self::Unsubscribe,
            Self::GetPeerAddresses,
            Self::AddPeer,
            Self::BanPeer,
            Self::UnbanPeer,
            Self::Shutdown,
        ]
    }
}
