[chain]
chain_id = 2

[node]
name = "misaka-seed-01"
mode = "seed"
data_dir = "../data/seed"
log_level = "info"

[p2p]
port = 6690
max_inbound_peers = 128
max_outbound_peers = 32
# advertise_addr = "YOUR_PUBLIC_IP:6690"

[rpc]
port = 3011

[consensus]
block_time_secs = 60
validator = false
validator_index = 0
validators = 1

[bootstrap]
seed_nodes = []
seed_file = "./seeds.txt"
reconnect_interval_secs = 30

[genesis]
timestamp_ms = 1773446400000
