#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

default_extended_harness_dir() {
  mktemp -d "${repo_root}/.tmp/dag-release-gate-extended.XXXXXX"
}

default_extended_target_dir() {
  mktemp -d "${repo_root}/.tmp/dag-release-gate-extended-target.XXXXXX"
}

default_extended_gate_dir() {
  mktemp -d "${repo_root}/.tmp/dag-release-gate-extended.XXXXXX"
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<'EOF'
MISAKA DAG extended release rehearsal

Usage:
  ./scripts/dag_release_gate_extended.sh

Purpose:
  Run the standard release gate with the optional 3-validator durable restart
  stage enabled explicitly.

This wrapper keeps the default release gate unchanged while making the extended
rehearsal path intentional.

The extended path skips the known-fragile 2-validator natural restart prelude
and then runs the optional 3-validator stage with a stable operator profile.
It also relaxes the durable-restart harness wait windows so the rehearsal can
absorb slower local convergence without changing consensus semantics.

Operator profile defaults for the extended rehearsal:
  - unique harness dir under ./.tmp/dag-release-gate-extended.XXXXXX
  - unique release gate dir under ./.tmp/dag-release-gate-extended.XXXXXX
  - unique cargo target dir under ./.tmp/dag-release-gate-extended-target.XXXXXX
  - checkpoint interval defaults to 12 unless overridden
  - wait attempts default to 360 unless overridden
  - polling defaults to 3s unless overridden
  - dedicated RPC ports 5711 / 5712 / 5713
  - dedicated P2P ports 9212 / 9213 / 9214
EOF
  exit 0
fi

if [[ $# -ne 0 ]]; then
  echo "usage: ./scripts/dag_release_gate_extended.sh" >&2
  exit 1
fi

echo "[gate] running extended release rehearsal (explicit 3-validator stage)"
extended_gate_dir="${MISAKA_EXTENDED_RELEASE_GATE_DIR:-$(default_extended_gate_dir)}"
extended_harness_dir="${MISAKA_EXTENDED_HARNESS_DIR:-$(default_extended_harness_dir)}"
extended_target_dir="${MISAKA_EXTENDED_CARGO_TARGET_DIR:-$(default_extended_target_dir)}"
exec env \
  MISAKA_RELEASE_GATE_PROFILE=extended \
  MISAKA_RELEASE_GATE_DIR="${extended_gate_dir}" \
  MISAKA_RUN_THREE_VALIDATOR_RESTART=1 \
  MISAKA_SKIP_NATURAL_DURABLE_RESTART=1 \
  MISAKA_DAG_CHECKPOINT_INTERVAL="${MISAKA_EXTENDED_DAG_CHECKPOINT_INTERVAL:-12}" \
  MISAKA_THREE_VALIDATOR_CHECKPOINT_INTERVAL="${MISAKA_THREE_VALIDATOR_CHECKPOINT_INTERVAL:-12}" \
  MISAKA_INITIAL_WAIT_ATTEMPTS="${MISAKA_EXTENDED_INITIAL_WAIT_ATTEMPTS:-360}" \
  MISAKA_RESTART_WAIT_ATTEMPTS="${MISAKA_EXTENDED_RESTART_WAIT_ATTEMPTS:-360}" \
  MISAKA_POLL_INTERVAL_SECS="${MISAKA_EXTENDED_POLL_INTERVAL_SECS:-3}" \
  MISAKA_RECOVERY_RESTART_DIR="${MISAKA_EXTENDED_RECOVERY_RESTART_DIR:-${extended_gate_dir}/recovery-restart}" \
  MISAKA_RECOVERY_HARNESS_DIR="${MISAKA_EXTENDED_RECOVERY_HARNESS_DIR:-${extended_gate_dir}/recovery-multinode}" \
  MISAKA_HARNESS_DIR="${extended_harness_dir}" \
  MISAKA_CARGO_TARGET_DIR="${extended_target_dir}" \
  MISAKA_RUN_SHIELDED_VK_MANIFEST="${MISAKA_RUN_SHIELDED_VK_MANIFEST:-1}" \
  MISAKA_SHIELDED_VK_MANIFEST_DIR="${MISAKA_SHIELDED_VK_MANIFEST_DIR:-${extended_gate_dir}/shielded-vk-manifest}" \
  MISAKA_SHIELDED_INCLUDE_BOUNDED_SHA3="${MISAKA_SHIELDED_INCLUDE_BOUNDED_SHA3:-1}" \
  MISAKA_SHIELDED_INCLUDE_BOUNDED_GROTH16="${MISAKA_SHIELDED_INCLUDE_BOUNDED_GROTH16:-1}" \
  MISAKA_SHIELDED_INCLUDE_BOUNDED_PLONK="${MISAKA_SHIELDED_INCLUDE_BOUNDED_PLONK:-1}" \
  MISAKA_SHIELDED_INCLUDE_BOUNDED_PLONK_THREE_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_BOUNDED_PLONK_THREE_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_BOUNDED_SHA3_THREE_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_BOUNDED_SHA3_THREE_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_BOUNDED_GROTH16_THREE_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_BOUNDED_GROTH16_THREE_VALIDATOR:-1}" \
  MISAKA_SHIELDED_REFRESH_BOUNDED_LIVE="${MISAKA_SHIELDED_REFRESH_BOUNDED_LIVE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_THREE_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_THREE_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_FOUR_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_FOUR_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_SIX_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_SIX_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_THREE_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_THREE_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_THREE_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_THREE_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_SIX_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_SIX_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_SIX_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_SIX_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_THREE_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_THREE_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_THREE_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_THREE_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_THREE_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_THREE_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_FOUR_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_FOUR_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_FOUR_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_FOUR_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_FOUR_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_FOUR_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_SIX_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_SIX_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_SIX_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_SIX_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_SIX_VALIDATOR_SEQUENCE="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_PLONK_SIX_VALIDATOR_SEQUENCE:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_FOUR_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_SHA3_FOUR_VALIDATOR:-1}" \
  MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_FOUR_VALIDATOR="${MISAKA_SHIELDED_INCLUDE_FULL_PATH_GROTH16_FOUR_VALIDATOR:-1}" \
  MISAKA_SHIELDED_REFRESH_FULL_PATH="${MISAKA_SHIELDED_REFRESH_FULL_PATH:-1}" \
  MISAKA_SHIELDED_INCLUDE_RUNTIME_COMPARISON="${MISAKA_SHIELDED_INCLUDE_RUNTIME_COMPARISON:-1}" \
  MISAKA_SHIELDED_REFRESH_RUNTIME_COMPARISON="${MISAKA_SHIELDED_REFRESH_RUNTIME_COMPARISON:-1}" \
  MISAKA_NODE_A_RPC_PORT="${MISAKA_EXTENDED_NODE_A_RPC_PORT:-5711}" \
  MISAKA_NODE_B_RPC_PORT="${MISAKA_EXTENDED_NODE_B_RPC_PORT:-5712}" \
  MISAKA_NODE_C_RPC_PORT="${MISAKA_EXTENDED_NODE_C_RPC_PORT:-5713}" \
  MISAKA_NODE_A_P2P_PORT="${MISAKA_EXTENDED_NODE_A_P2P_PORT:-9212}" \
  MISAKA_NODE_B_P2P_PORT="${MISAKA_EXTENDED_NODE_B_P2P_PORT:-9213}" \
  MISAKA_NODE_C_P2P_PORT="${MISAKA_EXTENDED_NODE_C_P2P_PORT:-9214}" \
  bash scripts/dag_release_gate.sh
